### PR TITLE
Moved tests from httpBin to Nock

### LINKED ISSUE #44: Replace HttpBin with Nock
https://github.com/nock/nock

### PR DESCRIPTION
**Pull request by damccorm**
Switched tests to use nock to spoof Http requests instead of connecting to httpBin. Eliminates timeout failures for tests and allows offline testing.

Resolves #44

### CODE REVIEW

**Comment by stephenmichaelf** [comment]
Looks good. Did we want to keep the original ones too as L2 tests @bryanmacfarlane ? We should set a pattern and then we can follow it everywhere. I am fine with L0 using nock then L2 using httpbin that runs during CI. Those tests will have less surface area than L0 but give us more thorough testing.

**Comment by bryanmacfarlane** [comment]
Yeah I think we want to keep the other tests but technically L1 (since we don't need a full agent etc... but it does real work).  We need a way to scope when running

**Comment by damccorm** [comment]
I added them back as L1, not sure if this is the best way to scope what tests are running though. I'm not super familiar with the make.js syntax/capabilities, so I'm definitely open to suggestions for a better way.

**Comment by stephenmichaelf** [comment]
We should also update the build definition to run these tests in ci. Right now this one uses the UI build definition style but we can talk about converting to yaml.

**Pull request merged**
