### PR TITLE
Better error logging when tool download fails

### PR DESCRIPTION
**Pull request by keithrob**

### CODE REVIEW

**Comment by stephenmichaelf** [comment]
Can we remove the extra spaces? May be helpful to surround the filename in quotes. Otherwise LGTM.

**Comment by keithrob** [comment]
@stephenmichaelf , I've added quotes.  Not sure what you mean by "remove extra spaces".

**Comment by stephenmichaelf** [comment]
@keithrob I was seeing extra spaces on several areas in the file, not sure why:

image

Not a huge deal but I saw them in 10 or so spots so wanted to mention it.

**Comment by keithrob** [comment]
@stephenmichaelf,
Those aren't added whitespaces those are removed whitespaces.  Which is generally a good idea.  Trailing whitespaces aren't helpful in code which is why most editors remove them (e.g. vscode).
Keith

**Pull request merged**
